runtime: python39  # or python310 depending on your Python version
entrypoint: gunicorn -b :8080 main:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  GOOGLE_API_KEY: ${GOOGLE_API_KEY}
  PORT: "8080"

handlers:
- url: /.*
  script: auto 