// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH4Fi1F9fJpRn_ePSGbD2AJPVYFKdomv0',
    appId: '1:873861567763:web:22e7adcf79d180cd96b6e6',
    messagingSenderId: '873861567763',
    projectId: 'saheli-db8a5',
    authDomain: 'saheli-db8a5.firebaseapp.com',
    storageBucket: 'saheli-db8a5.appspot.com',
    measurementId: 'G-EDJH4NTMCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV3wv9Izo56-1N0q0jfk0j-yHdiZgf8Xo',
    appId: '1:873861567763:android:35b9a6bdb2b6c23b96b6e6',
    messagingSenderId: '873861567763',
    projectId: 'saheli-db8a5',
    storageBucket: 'saheli-db8a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzX7RgNblljRFZ17jA118IHE9im0GM5_o',
    appId: '1:873861567763:ios:01d914f7c574475396b6e6',
    messagingSenderId: '873861567763',
    projectId: 'saheli-db8a5',
    storageBucket: 'saheli-db8a5.appspot.com',
    iosClientId: '873861567763-pa1ds9mm7nuekhf3l4f6f6fnp9gnfm2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.saheliApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzX7RgNblljRFZ17jA118IHE9im0GM5_o',
    appId: '1:873861567763:ios:19327cf1d1c4306096b6e6',
    messagingSenderId: '873861567763',
    projectId: 'saheli-db8a5',
    storageBucket: 'saheli-db8a5.appspot.com',
    iosClientId: '873861567763-hv6v9a66sokhum14sqvbnikeiup9e5aj.apps.googleusercontent.com',
    iosBundleId: 'com.example.saheliApp.RunnerTests',
  );
}
