// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2GhrpFgTp9OTLDAOrhwXpMAPYwoXw-Bc',
    appId: '1:556589186491:web:188592933a43a2087b189e',
    messagingSenderId: '556589186491',
    projectId: 'saheli-v2',
    authDomain: 'saheli-v2.firebaseapp.com',
    storageBucket: 'saheli-v2.appspot.com',
    measurementId: 'G-RPN2LV746V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4W_1I3rooA_x4zLmfzd_Uo6DWQ2NnBgs',
    appId: '1:556589186491:android:64e96ebff313df657b189e',
    messagingSenderId: '556589186491',
    projectId: 'saheli-v2',
    storageBucket: 'saheli-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTr7Bg5qm9XO2V9LDFFKS-PI3Wqf5TDbw',
    appId: '1:556589186491:ios:c14b113207f9a5367b189e',
    messagingSenderId: '556589186491',
    projectId: 'saheli-v2',
    storageBucket: 'saheli-v2.appspot.com',
    androidClientId: '556589186491-g5c8vr2taas988u0cujj1nrhccj499gb.apps.googleusercontent.com',
    iosClientId: '556589186491-tac4p313l6vla8mioj2p2phbttnbgqek.apps.googleusercontent.com',
    iosBundleId: 'com.example.saheliApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTr7Bg5qm9XO2V9LDFFKS-PI3Wqf5TDbw',
    appId: '1:556589186491:ios:9363b477186db3467b189e',
    messagingSenderId: '556589186491',
    projectId: 'saheli-v2',
    storageBucket: 'saheli-v2.appspot.com',
    androidClientId: '556589186491-g5c8vr2taas988u0cujj1nrhccj499gb.apps.googleusercontent.com',
    iosClientId: '556589186491-p53q4rdp4oqlh7bsm7j89o882mt34tj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.saheliApp.RunnerTests',
  );
}
